### ISSUE TITLE
[BUG REPORT] - Sim removed but not changed?

### ISSUE THREAD

**Issue by Albin323** [Maximus7474/lb-phone-simcards#2]
**Describe the bug**
Simcard is removed but says that it can't make a new number due to no export.

**To Reproduce**
1. Go to 'Anywhere'
2. Click on 'Use'
3. Scroll down to 'Nothing?'

**Expected behavior**
It shoulden't remove the simcard if it can't change the number

**Screenshots**
![image](https://github.com/user-attachments/assets/9e3bb34f-2036-4a74-99b1-6ea82cda8ade)
**Additional context**
Looks good so far.

**Comment by Maximus7474** [comment]
I can make it a call-back, but the reason there's no real need for it is because the issue would 95% of the time be because of an incorrect installation.

**Comment by Albin323** [comment]
> I can make it a call-back, but the reason there's no real need for it is because the issue would 95% of the time be because of an incorrect installation.

Yeah. I understood that later on.

Also doesn't seem like the config stuff does anyting (haven't tested the item part)

**Comment by Maximus7474** [comment]
> Also doesn't seem like the config stuff does anyting (haven't tested the item part)

Which config "stuff" ?

**Comment by Albin323** [comment]
> > Also doesn't seem like the config stuff does anyting (haven't tested the item part)
> 
> Which config "stuff" ?

Config = exports["lb-phone"]:GetConfig()

Config.SimCard = {

    ItemName = 'simcard',

    --[[
        If set to true, it will put the phone's number back to the simcard
        If set to false, it will consume/delete the simcard item
    ]]
    ReplaceSimCardNumber = false,

    --[[ 
        Delete the simcard item after use, only used if ReplaceSimCardNumber is set to false
    ]]
    DeleteSimCard = false,
}

or alteast "ReplaceSimCardNumber" and "DeleteSimCard"

Turning, repalce to true did nothing. and it deletes the sim card no matter what.

**Comment by Maximus7474** [comment]
How is your item defined in ox_inventory ?

**Comment by Maximus7474** [comment]
It's because of me not having put the consume parameter in the template, it defaults to 1 and not 0.

**Comment by Maximus7474** [comment]
Patched in v0.1.5

**Comment by Albin323** [comment]
> How is your item defined in ox_inventory ?

It's just copied and pasted.



> Patched in v0.1.5

Just tested, still doesn't seem to change anything.

Like yes, the phone updates but the simcards gets removed even if i tell it not to through config.

**Comment by Maximus7474** [comment]
You'll need to change the item to the new configuration.

> It's because of me not having put the consume parameter in the template, it defaults to 1 and not 0.

**Comment by Albin323** [comment]
> You'll need to change the item to the new configuration.

Oh, now i got what you meant. Will have a look. :)

**Comment by Albin323** [comment]
> Oh, now i got what you meant. Will have a look. :)

Works great now except the fact that you can't change back.

The card gets the new data. But it needs to check if the data is already in the DB and then take it instead of creating a new one. (and ofc create a new one if there isn't one)

Other then that

Works flawlessly what i can see.

**Comment by Albin323** [comment]
Fixed. Fast and good work @Maximus7474 !
